# Generated by Django 4.2.3 on 2024-01-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('PHOTOGRAPHER', 'Photographer'), ('VIDEOGRAPHER', 'Videographer'), ('DJ', 'DJ'), ('PHOTOBOOTH OPERATOR', 'Photobooth Operator'), ('ADMIN', 'Admin'), ('SALES PERSON', 'Sales Person'), ('MANAGER', 'Manager')], max_length=50, unique=True),
        ),
    ]
