# Generated by Django 4.2.3 on 2024-11-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0002_customuser_additional_roles_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='services.servicetype'),
        ),
    ]
