# Generated by Django 4.2.3 on 2024-03-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0030_alter_eventstaffbooking_role'),
        ('users', '0005_customuser_city_customuser_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='contracts.servicetype'),
            preserve_default=False,
        ),
    ]
