# Generated by Django 4.2.3 on 2024-04-06 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='primary_phone1',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='primary_phone2',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
    ]
