# Generated by Django 4.2.3 on 2024-04-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_primary_phone1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('PHOTOGRAPHER', 'Photographer'), ('VIDEOGRAPHER', 'Videographer'), ('DJ', 'Dj'), ('PHOTOBOOTH OPERATOR', 'Photobooth Operator'), ('ADMIN', 'Admin'), ('SALES PERSON', 'Sales Person'), ('MANAGER', 'Manager'), ('COORDINATOR', 'Coordinator'), ('CLIENT', 'Client')], max_length=50, unique=True),
        ),
    ]
