# Generated by Django 4.2.3 on 2024-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_primary_phone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_roles',
            field=models.ManyToManyField(blank=True, related_name='additional_users', to='users.role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.IntegerField(default=0, help_text='Determines the order of photographers.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('client', 'Client')], default='client', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('PHOTOGRAPHER', 'Photographer'), ('VIDEOGRAPHER', 'Videographer'), ('DJ', 'Dj'), ('PHOTOBOOTH OPERATOR', 'Photobooth Operator'), ('ADMIN', 'Admin'), ('SALES PERSON', 'Sales Person'), ('MANAGER', 'Manager'), ('COORDINATOR', 'Coordinator'), ('CLIENT', 'Client'), ('PROSPECT1', 'Prospect Photographer 1'), ('PROSPECT2', 'Prospect Photographer 2'), ('PROSPECT3', 'Prospect Photographer 3')], max_length=50, unique=True),
        ),
    ]
