# Generated by Django 4.2.3 on 2024-04-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_roles',
            field=models.ManyToManyField(blank=True, related_name='additional_users', to='users.role'),
        ),
    ]
