# Generated by Django 4.2.3 on 2024-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_additional_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('PHOTOGRAPHER', 'Photographer'), ('VIDEOGRAPHER', 'Videographer'), ('DJ', 'Dj'), ('PHOTOBOOTH OPERATOR', 'Photobooth Operator'), ('ADMIN', 'Admin'), ('SALES PERSON', 'Sales Person'), ('MANAGER', 'Manager'), ('COORDINATOR', 'Coordinator'), ('CLIENT', 'Client'), ('PROSPECT1', 'Prospect Photographer 1'), ('PROSPECT2', 'Prospect Photographer 2'), ('PROSPECT3', 'Prospect Photographer 3')], max_length=50, unique=True),
        ),
    ]
