# Generated by Django 4.2.3 on 2024-04-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.IntegerField(default=0, help_text='Determines the order of photographers.'),
        ),
    ]
