# Generated by Django 4.2.3 on 2024-06-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_additional_roles_customuser_rank_and_more'),
        ('users', '0014_alter_customuser_user_type'),
    ]

    operations = [
    ]
