# Generated by Django 4.2.3 on 2024-06-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_status'),
        ('users', '0015_merge_20240610_0937'),
    ]

    operations = [
    ]
