# Generated by Django 4.2.3 on 2024-11-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0006_delete_weddingdayguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingDayGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('primary_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('partner_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('partner_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dressing_location', models.CharField(blank=True, max_length=255, null=True)),
                ('dressing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('dressing_start_time', models.TimeField(blank=True, null=True)),
                ('ceremony_site', models.CharField(blank=True, max_length=255, null=True)),
                ('ceremony_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ceremony_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('ceremony_start', models.TimeField(blank=True, null=True)),
                ('ceremony_end', models.TimeField(blank=True, null=True)),
                ('reception_site', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_address', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('reception_start', models.TimeField(blank=True, null=True)),
                ('dinner_start', models.TimeField(blank=True, null=True)),
                ('reception_end', models.TimeField(blank=True, null=True)),
                ('staff_table', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop1', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop2', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop3', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop4', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer2_start_location', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer2_start_location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer2_start', models.TimeField(blank=True, null=True)),
                ('p1_attendant_of_honor', models.CharField(blank=True, max_length=255, null=True)),
                ('p1_attendant_qty', models.IntegerField(blank=True, null=True)),
                ('flower_attendant_qty', models.IntegerField(blank=True, null=True)),
                ('usher_qty', models.IntegerField(blank=True, null=True)),
                ('p2_attendant_of_honor', models.CharField(blank=True, max_length=255, null=True)),
                ('p2_attendant_qty', models.IntegerField(blank=True, null=True)),
                ('ring_bearer_qty', models.IntegerField(blank=True, null=True)),
                ('p1_parent_names', models.TextField(blank=True, max_length=255, null=True)),
                ('p1_sibling_names', models.TextField(blank=True, max_length=255, null=True)),
                ('p1_grandparent_names', models.TextField(blank=True, max_length=255, null=True)),
                ('p2_parent_names', models.TextField(blank=True, max_length=255, null=True)),
                ('p2_sibling_names', models.TextField(blank=True, max_length=255, null=True)),
                ('p2_grandparent_names', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request1', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request2', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request3', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request4', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request5', models.TextField(blank=True, max_length=255, null=True)),
                ('video_client_names', models.CharField(blank=True, max_length=255, null=True)),
                ('wedding_story_song_title', models.CharField(blank=True, max_length=255, null=True)),
                ('wedding_story_song_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('dance_montage_song_title', models.CharField(blank=True, max_length=255, null=True)),
                ('dance_montage_song_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('video_special_dances', models.TextField(blank=True, max_length=255, null=True)),
                ('photo_booth_text_line1', models.TextField(blank=True, max_length=255, null=True)),
                ('photo_booth_text_line2', models.TextField(blank=True, max_length=255, null=True)),
                ('photo_booth_placement', models.TextField(blank=True, max_length=255, null=True)),
                ('version_number', models.IntegerField(default=1)),
                ('submitted', models.BooleanField(default=False)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_day_guide', to='contracts.contract')),
            ],
        ),
    ]
