# Generated by Django 4.2.3 on 2024-01-06 00:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEventStaffOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('Photography', 'Photography'), ('Videography', 'Videography'), ('DJ', 'DJ'), ('Photobooth', 'Photobooth')], max_length=20)),
                ('default_text', models.TextField(blank=True, help_text='Default text for the staff option')),
                ('package_notes', models.TextField(blank=True, help_text='Additional notes for the staff option')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_taxable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('default_text', models.TextField(blank=True, help_text='Default text for products')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_contact', models.CharField(max_length=255)),
                ('primary_email', models.EmailField(max_length=254, unique=True)),
                ('primary_phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('primary_phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('primary_address1', models.CharField(max_length=255)),
                ('primary_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('partner_contact', models.CharField(max_length=255)),
                ('partner_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('partner_phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('partner_phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('alt_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('alt_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('status', models.CharField(choices=[('pipeline', 'Pipeline'), ('forecast', 'Forecast'), ('pending', 'Pending'), ('booked', 'Booked'), ('completed', 'Completed'), ('dead', 'Dead')], default='pipeline', max_length=10)),
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_contract_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('contract_date', models.DateField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('is_code_92', models.BooleanField(default=False, verbose_name='Code 92 Flag')),
                ('bridal_party_qty', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('guests_qty', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('lead_source', models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('REFERRAL', 'Referral')], max_length=20, null=True)),
                ('ceremony_site', models.CharField(blank=True, max_length=255, null=True)),
                ('ceremony_city', models.CharField(blank=True, max_length=255, null=True)),
                ('ceremony_state', models.CharField(blank=True, max_length=255, null=True)),
                ('ceremony_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('ceremony_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('ceremony_email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('reception_site', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_city', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_state', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('reception_email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('staff_notes', models.TextField(blank=True, null=True)),
                ('client_notes', models.TextField(blank=True, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ContractOvertime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='ContractProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('special_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('discount_type', models.CharField(choices=[('Package', 'Package Discounts'), ('Sunday', 'Sunday Discounts'), ('Other', 'Other Discounts')], default='Other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='EventStaffBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PHOTOGRAPHER1', 'Photographer 1'), ('PHOTOGRAPHER2', 'Photographer 2'), ('VIDEOGRAPHER1', 'Videographer 1'), ('VIDEOGRAPHER2', 'Videographer 2'), ('DJ1', 'DJ 1'), ('DJ2', 'DJ 2'), ('PHOTOBOOTH_OP', 'Photobooth Operator')], max_length=30)),
                ('hours_booked', models.PositiveIntegerField(blank=True, choices=[(2, '2 Hours'), (4, '4 Hours'), (8, '8 Hours')], help_text='Number of hours staff is booked for', null=True)),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('PENDING', 'Pending'), ('DECLINED', 'Declined'), ('APPROVED', 'Approved'), ('CLEARED', 'Cleared')], default='PENDING', max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('booking_notes', models.TextField(blank=True, help_text='Notes for event staff', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('address', models.CharField(max_length=255)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Note Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('PHOTOGRAPHY', 'Photography'), ('VIDEOGRAPHY', 'Videography'), ('DJ', 'DJ'), ('PHOTOBOOTH', 'Photobooth')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('package_type', models.CharField(choices=[('Photography', 'Photography'), ('Videography', 'Videography'), ('DJ', 'DJ'), ('Photobooth', 'Photobooth')], max_length=20)),
                ('default_text', models.TextField(blank=True, help_text='Default text for the package')),
                ('package_notes', models.TextField(blank=True, help_text='Additional notes for the package')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CREDIT_CARD', 'Credit Card'), ('ZELLE', 'Zelle'), ('VENMO', 'Venmo')], default='CASH', max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_identifier', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_taxable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.location')),
            ],
        ),
        migrations.CreateModel(
            name='StaffOvertime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('overtime_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.overtimeoption')),
            ],
        ),
    ]
