# Generated by Django 4.2.3 on 2024-01-06 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffovertime',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='note',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contracts.eventstaffbooking'),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='eventstaffbooking',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='eventstaffbooking',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_products', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_contracts', to='contracts.additionalproduct'),
        ),
        migrations.AddField(
            model_name='contractovertime',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractovertime',
            name='overtime_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.overtimeoption'),
        ),
        migrations.AddField(
            model_name='contract',
            name='additional_products',
            field=models.ManyToManyField(related_name='contracts', through='contracts.ContractProduct', to='contracts.additionalproduct'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.client'),
        ),
        migrations.AddField(
            model_name='contract',
            name='csr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='dj1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dj1_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='dj2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dj2_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='dj_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'type': 'DJ'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_dj_options', to='contracts.additionaleventstaffoption'),
        ),
        migrations.AddField(
            model_name='contract',
            name='dj_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'package_type': 'DJ'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dj_packages', to='contracts.package'),
        ),
        migrations.AddField(
            model_name='contract',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.location'),
        ),
        migrations.AddField(
            model_name='contract',
            name='other_discounts',
            field=models.ForeignKey(blank=True, limit_choices_to={'discount_type': 'Other', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_discounts', to='contracts.discount'),
        ),
        migrations.AddField(
            model_name='contract',
            name='overtime_options',
            field=models.ManyToManyField(related_name='contracts', through='contracts.ContractOvertime', to='contracts.overtimeoption'),
        ),
        migrations.AddField(
            model_name='contract',
            name='package_discounts',
            field=models.ForeignKey(blank=True, limit_choices_to={'discount_type': 'Package', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_discounts', to='contracts.discount'),
        ),
        migrations.AddField(
            model_name='contract',
            name='photobooth_op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='photobooth_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'package_type': 'Photobooth'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_packages', to='contracts.package'),
        ),
        migrations.AddField(
            model_name='contract',
            name='photographer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photographer1_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='photographer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photographer2_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='photography_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'type': 'Photography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_photography_options', to='contracts.additionaleventstaffoption'),
        ),
        migrations.AddField(
            model_name='contract',
            name='photography_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'package_type': 'Photography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photography_packages', to='contracts.package'),
        ),
        migrations.AddField(
            model_name='contract',
            name='prospect_photographer1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_photographer1_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='prospect_photographer2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_photographer2_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='prospect_photographer3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_photographer3_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='sunday_discounts',
            field=models.ForeignKey(blank=True, limit_choices_to={'discount_type': 'Sunday', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_discounts', to='contracts.discount'),
        ),
        migrations.AddField(
            model_name='contract',
            name='videographer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videographer1_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='videographer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videographer2_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='videography_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'type': 'Videography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_videography_options', to='contracts.additionaleventstaffoption'),
        ),
        migrations.AddField(
            model_name='contract',
            name='videography_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'package_type': 'Videography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videography_packages', to='contracts.package'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availability',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
