# Generated by Django 4.2.3 on 2024-08-17 02:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photography_service', models.CharField(blank=True, max_length=255, null=True)),
                ('videography_service', models.CharField(blank=True, max_length=255, null=True)),
                ('dj_service', models.CharField(blank=True, max_length=255, null=True)),
                ('photobooth_service', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='contract_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_client_visible', models.BooleanField(default=True, help_text='Check if this document should be visible to clients.')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('Package', 'Package Discounts'), ('Sunday', 'Sunday Discounts')], max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('discount_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='EngagementSessionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Deposit Amount')),
                ('default_text', models.TextField(blank=True, help_text='Default text for the package')),
                ('rider_text', models.TextField(blank=True, help_text='Rider for the package')),
                ('package_notes', models.TextField(blank=True, help_text='Additional notes for the package')),
            ],
        ),
        migrations.CreateModel(
            name='LeadSourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('schedule_a', 'Schedule A'), ('custom', 'Custom')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiderAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_type', models.CharField(max_length=50)),
                ('signature', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rider_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.paymentpurpose')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_payments', to='contracts.paymentschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('applied_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingDayGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('primary_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('partner_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('partner_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dressing_location', models.CharField(blank=True, max_length=255, null=True)),
                ('dressing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('dressing_start_time', models.TimeField(blank=True, null=True)),
                ('ceremony_site', models.CharField(blank=True, max_length=255, null=True)),
                ('ceremony_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ceremony_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('ceremony_start', models.TimeField(blank=True, null=True)),
                ('ceremony_end', models.TimeField(blank=True, null=True)),
                ('reception_site', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_address', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('reception_start', models.TimeField(blank=True, null=True)),
                ('dinner_start', models.TimeField(blank=True, null=True)),
                ('reception_end', models.TimeField(blank=True, null=True)),
                ('staff_table', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop1', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop2', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop3', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop4', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer2_start_location', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer2_start_location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer2_start', models.TimeField(blank=True, null=True)),
                ('p1_attendant_of_honor', models.CharField(blank=True, max_length=255, null=True)),
                ('p1_attendant_qty', models.IntegerField(blank=True, null=True)),
                ('flower_attendant_qty', models.IntegerField(blank=True, null=True)),
                ('usher_qty', models.IntegerField(blank=True, null=True)),
                ('p2_attendant_of_honor', models.CharField(blank=True, max_length=255, null=True)),
                ('p2_attendant_qty', models.IntegerField(blank=True, null=True)),
                ('ring_bearer_qty', models.IntegerField(blank=True, null=True)),
                ('p1_parent_names', models.TextField(blank=True, max_length=255, null=True)),
                ('p1_sibling_names', models.TextField(blank=True, max_length=255, null=True)),
                ('p1_grandparent_names', models.TextField(blank=True, max_length=255, null=True)),
                ('p2_parent_names', models.TextField(blank=True, max_length=255, null=True)),
                ('p2_sibling_names', models.TextField(blank=True, max_length=255, null=True)),
                ('p2_grandparent_names', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request1', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request2', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request3', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request4', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request5', models.TextField(blank=True, max_length=255, null=True)),
                ('video_client_names', models.CharField(blank=True, max_length=255, null=True)),
                ('wedding_story_song_title', models.CharField(blank=True, max_length=255, null=True)),
                ('wedding_story_song_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('dance_montage_song_title', models.CharField(blank=True, max_length=255, null=True)),
                ('dance_montage_song_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('video_special_dances', models.TextField(blank=True, max_length=255, null=True)),
                ('photo_booth_text_line1', models.TextField(blank=True, max_length=255, null=True)),
                ('photo_booth_text_line2', models.TextField(blank=True, max_length=255, null=True)),
                ('photo_booth_placement', models.TextField(blank=True, max_length=255, null=True)),
                ('version_number', models.IntegerField(default=1)),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='client_notes',
            new_name='custom_text',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_type',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='additionaleventstaffoption',
            name='type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='lead_source',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='package_discounts',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='photobooth_op',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='sunday_discounts',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='overtimeoption',
            name='type',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_type',
        ),
        migrations.AddField(
            model_name='additionaleventstaffoption',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Deposit Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionaleventstaffoption',
            name='hours',
            field=models.IntegerField(default=0, verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='additionaleventstaffoption',
            name='rider_text',
            field=models.TextField(blank=True, help_text='Rider for the package'),
        ),
        migrations.AddField(
            model_name='availability',
            name='always_off_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='contract',
            name='booked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_coordinated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='lead_source_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='old_contract_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='package_discount_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contract',
            name='photobooth_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Photobooth'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_photobooth_options', to='contracts.additionaleventstaffoption'),
        ),
        migrations.AddField(
            model_name='contract',
            name='photobooth_op1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_op1_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='photobooth_op2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_op2_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='sunday_discount_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='discount',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimeoption',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Deposit Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='hours',
            field=models.IntegerField(default=0, verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='package',
            name='rider_text',
            field=models.TextField(blank=True, help_text='Rider for the package'),
        ),
        migrations.AddField(
            model_name='payment',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='modified_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffovertime',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'photographer1'), ('PHOTOGRAPHER2', 'photographer2'), ('VIDEOGRAPHER1', 'videographer1'), ('VIDEOGRAPHER2', 'videographer2'), ('DJ1', 'dj1'), ('DJ2', 'dj2'), ('PHOTOBOOTH_OP1', 'photobooth_op1'), ('PHOTOBOOTH_OP2', 'photobooth_op2'), ('PROSPECT1', 'prospect_photographer1'), ('PROSPECT2', 'prospect_photographer2'), ('PROSPECT3', 'prospect_photographer3'), ('ENGAGEMENT', 'engagement')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='partner_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='partner_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='client',
            name='partner_phone1',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='partner_phone2',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_phone1',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_phone2',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ceremony_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dj_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Dj'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_dj_options', to='contracts.additionaleventstaffoption'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dj_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Dj'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dj_packages', to='contracts.package'),
        ),
        migrations.RemoveField(
            model_name='contract',
            name='other_discounts',
        ),
        migrations.AlterField(
            model_name='contract',
            name='photobooth_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Photobooth'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_packages', to='contracts.package'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photography_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Photography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_photography_options', to='contracts.additionaleventstaffoption'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photography_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Photography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photography_packages', to='contracts.package'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='reception_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pipeline', 'Pipeline'), ('forecast', 'Forecast'), ('booked', 'Booked'), ('completed', 'Completed'), ('dead', 'Dead')], default='pipeline', max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='videography_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Videography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_videography_options', to='contracts.additionaleventstaffoption'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='videography_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Videography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videography_packages', to='contracts.package'),
        ),
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='booking_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='hours_booked',
            field=models.PositiveIntegerField(blank=True, choices=[(2, '2 Hours'), (4, '4 Hours'), (8, '8 Hours')], null=True),
        ),
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'Photographer 1'), ('PHOTOGRAPHER2', 'Photographer 2'), ('ENGAGEMENT', 'Engagement'), ('VIDEOGRAPHER1', 'Videographer 1'), ('VIDEOGRAPHER2', 'Videographer 2'), ('DJ1', 'DJ 1'), ('DJ2', 'DJ 2'), ('PHOTOBOOTH_OP1', 'Photobooth Operator 1'), ('PHOTOBOOTH_OP2', 'Photobooth Operator 2'), ('PROSPECT1', 'Prospect Photographer 1'), ('PROSPECT2', 'Prospect Photographer 2'), ('PROSPECT3', 'Prospect Photographer 3')], max_length=30),
        ),
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='status',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('CLEARED', 'Cleared')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='overtimeoption',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'photographer1'), ('PHOTOGRAPHER2', 'photographer2'), ('VIDEOGRAPHER1', 'videographer1'), ('VIDEOGRAPHER2', 'videographer2'), ('DJ1', 'dj1'), ('DJ2', 'dj2'), ('PHOTOBOOTH_OP1', 'photobooth_op1'), ('PHOTOBOOTH_OP2', 'photobooth_op2'), ('PROSPECT1', 'prospect_photographer1'), ('PROSPECT2', 'prospect_photographer2'), ('PROSPECT3', 'prospect_photographer3'), ('ENGAGEMENT', 'engagement')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='eventstaffbooking',
            unique_together={('contract', 'role')},
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_day_guide', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='servicefee',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicefees', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='servicefee',
            name='fee_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.servicefeetype'),
        ),
        migrations.AddField(
            model_name='rideragreement',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_agreements', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='engagementsessionoption',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_session_options', to='contracts.servicetype'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractagreement',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_agreements', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractagreement',
            name='photographer_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changelog',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additionaleventstaffoption',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_staff_options', to='contracts.servicetype'),
        ),
        migrations.AddField(
            model_name='contract',
            name='engagement_session',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_session_options', to='contracts.engagementsessionoption'),
        ),
        migrations.AddField(
            model_name='contract',
            name='lead_source_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.leadsourcecategory'),
        ),
        migrations.AddField(
            model_name='discount',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.servicetype'),
        ),
        migrations.AddField(
            model_name='overtimeoption',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='overtime_options', to='contracts.servicetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='contracts.servicetype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.paymentpurpose'),
        ),
        migrations.AddField(
            model_name='contract',
            name='other_discounts',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='contracts.discount'),
        ),
    ]
