# Generated by Django 4.2.3 on 2024-01-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=8, verbose_name='Deposit Amount'),
            preserve_default=False,
        ),
    ]
