# Generated by Django 4.2.3 on 2024-01-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_package_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaleventstaffoption',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8, verbose_name='Deposit Amount'),
            preserve_default=False,
        ),
    ]
