# Generated by Django 4.2.3 on 2024-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_changelog_contractagreement_contractdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdocument',
            name='is_event_staff_visible',
            field=models.BooleanField(default=False, help_text='Check if this document should be visible to event staff.'),
        ),
    ]
