# Generated by Django 4.2.3 on 2024-11-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contractdocument_is_event_staff_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='staff',
        ),
        migrations.AlterUniqueTogether(
            name='eventstaffbooking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventstaffbooking',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='eventstaffbooking',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='EventStaffBooking',
        ),
    ]
