# Generated by Django 4.2.3 on 2024-11-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_remove_availability_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeddingDayGuide',
        ),
    ]
