# Generated by Django 4.2.3 on 2024-11-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_delete_weddingdayguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractdocument',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='rideragreement',
            name='contract',
        ),
        migrations.DeleteModel(
            name='ContractAgreement',
        ),
        migrations.DeleteModel(
            name='ContractDocument',
        ),
        migrations.DeleteModel(
            name='RiderAgreement',
        ),
    ]
