# Generated by Django 4.2.3 on 2024-01-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contractdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdocument',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
