# Generated by Django 4.2.3 on 2024-11-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_remove_contractdocument_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentschedule',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='schedulepayment',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='schedulepayment',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentPurpose',
        ),
        migrations.DeleteModel(
            name='PaymentSchedule',
        ),
        migrations.DeleteModel(
            name='SchedulePayment',
        ),
    ]
