# Generated by Django 4.2.3 on 2024-01-18 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contractdocument_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementSessionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Deposit Amount')),
                ('default_text', models.TextField(blank=True, help_text='Default text for the package')),
                ('package_notes', models.TextField(blank=True, help_text='Additional notes for the package')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='photography_engagement_session',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'type': 'Photography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_session_options', to='contracts.engagementsessionoption'),
        ),
    ]
