# Generated by Django 4.2.3 on 2024-01-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_engagementsessionoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='photography_engagement_session',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_session_options', to='contracts.engagementsessionoption'),
        ),
    ]
