# Generated by Django 4.2.3 on 2024-01-21 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_contract_photography_engagement_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='photography_engagement_session',
            new_name='engagement_session',
        ),
    ]
