# Generated by Django 4.2.3 on 2024-01-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_rename_photography_engagement_session_contract_engagement_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='client_notes',
        ),
        migrations.DeleteModel(
            name='CommunicationLog',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
