# Generated by Django 4.2.3 on 2024-01-29 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_remove_note_booking_remove_note_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='partner_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
