# Generated by Django 4.2.3 on 2024-01-29 17:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_client_partner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='partner_phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
