# Generated by Django 4.2.3 on 2024-11-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_remove_contractproduct_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaleventstaffoption',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='contractovertime',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contractovertime',
            name='overtime_option',
        ),
        migrations.RemoveField(
            model_name='engagementsessionoption',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='overtimeoption',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='package',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='staffovertime',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='staffovertime',
            name='overtime_option',
        ),
        migrations.RemoveField(
            model_name='staffovertime',
            name='staff_member',
        ),
    ]
