# Generated by Django 4.2.3 on 2024-11-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_remove_additionaleventstaffoption_service_type_and_more'),
        ('users', '0003_alter_role_service_type'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dj_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Dj'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_dj_options', to='services.additionaleventstaffoption'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dj_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Dj'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dj_packages', to='services.package'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='engagement_session',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_session_options', to='services.engagementsessionoption'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='overtime_options',
            field=models.ManyToManyField(related_name='contracts', through='services.ContractOvertime', to='services.overtimeoption'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photobooth_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Photobooth'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_photobooth_options', to='services.additionaleventstaffoption'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photobooth_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Photobooth'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_packages', to='services.package'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photography_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Photography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_photography_options', to='services.additionaleventstaffoption'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photography_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Photography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photography_packages', to='services.package'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='videography_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Videography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_videography_options', to='services.additionaleventstaffoption'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='videography_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Videography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videography_packages', to='services.package'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicetype'),
        ),
        migrations.DeleteModel(
            name='AdditionalEventStaffOption',
        ),
        migrations.DeleteModel(
            name='ContractOvertime',
        ),
        migrations.DeleteModel(
            name='EngagementSessionOption',
        ),
        migrations.DeleteModel(
            name='OvertimeOption',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='StaffOvertime',
        ),
    ]
