# Generated by Django 4.2.3 on 2025-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formalwear', '0002_formalwearproduct_default_text_and_more'),
        ('contracts', '0014_alter_contract_dj_additional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='formalwear_products',
            field=models.ManyToManyField(related_name='contracts', through='formalwear.ContractFormalwearProduct', to='formalwear.formalwearproduct'),
        ),
    ]
