# Generated by Django 4.2.3 on 2024-02-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages_new', to='contracts.servicetype'),
        ),
    ]
