# Generated by Django 4.2.3 on 2024-02-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_auto_20240209_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_type',
        ),
    ]
