# Generated by Django 4.2.3 on 2024-02-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_remove_old_package_type_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_type_new',
            new_name='package_type',
        ),
    ]
