# Generated by Django 4.2.3 on 2024-02-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_rename_package_type_new_to_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dj_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'package_type__name': 'DJ'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dj_packages', to='contracts.package'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photobooth_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'package_type__name': 'Photobooth'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_packages', to='contracts.package'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photography_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'package_type__name': 'Photography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photography_packages', to='contracts.package'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='videography_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'package_type__name': 'Videography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videography_packages', to='contracts.package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='contracts.servicetype'),
        ),
    ]
