# Generated by Django 4.2.3 on 2024-02-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_alter_contract_dj_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaleventstaffoption',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages_new', to='contracts.servicetype'),
        ),
    ]
