# Generated by Django 4.2.3 on 2024-02-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_auto_20240209_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaleventstaffoption',
            name='type',
        ),
    ]
