# Generated by Django 4.2.3 on 2024-02-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_remove_old_type_fieldld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaleventstaffoption',
            name='service_type',
        ),
        migrations.AddField(
            model_name='additionaleventstaffoption',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_staff_options', to='contracts.servicetype'),
        ),
    ]
