# Generated by Django 4.2.3 on 2024-02-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_rename_service_type_new_to_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaleventstaffoption',
            old_name='type',
            new_name='service_type',
        ),
    ]
