# Generated by Django 4.2.3 on 2024-02-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0025_rename_type_to_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_type',
            new_name='service_type',
        ),
    ]
