# Generated by Django 4.2.3 on 2024-02-12 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_rename_package_type_package_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimeoption',
            name='type',
        ),
        migrations.AddField(
            model_name='overtimeoption',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='overtime_options', to='contracts.servicetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='dj_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'DJ'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_dj_options', to='contracts.additionaleventstaffoption'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dj_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'DJ'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dj_packages', to='contracts.package'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photobooth_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Photobooth'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_packages', to='contracts.package'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photography_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Photography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_photography_options', to='contracts.additionaleventstaffoption'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photography_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Photography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photography_packages', to='contracts.package'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='videography_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Videography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_videography_options', to='contracts.additionaleventstaffoption'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='videography_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Videography'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videography_packages', to='contracts.package'),
        ),
    ]
