# Generated by Django 4.2.3 on 2024-02-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_remove_overtimeoption_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Hours'),
        ),
    ]
