# Generated by Django 4.2.3 on 2024-02-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0028_package_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaleventstaffoption',
            name='hours',
            field=models.IntegerField(default=0, verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='package',
            name='hours',
            field=models.IntegerField(default=0, verbose_name='Hours'),
        ),
    ]
