# Generated by Django 4.2.3 on 2024-02-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_additionaleventstaffoption_hours_alter_package_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'Photographer 1'), ('PHOTOGRAPHER2', 'Photographer 2'), ('ENGAGEMENT', 'Engagement'), ('VIDEOGRAPHER1', 'Videographer 1'), ('VIDEOGRAPHER2', 'Videographer 2'), ('DJ1', 'DJ 1'), ('DJ2', 'DJ 2'), ('PHOTOBOOTH_OP', 'Photobooth Operator')], max_length=30),
        ),
    ]
