# Generated by Django 4.2.3 on 2024-03-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0030_alter_eventstaffbooking_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dj_package',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Dj'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dj_packages', to='contracts.package'),
        ),
    ]
