# Generated by Django 4.2.3 on 2024-03-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_alter_contract_dj_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='photobooth_additional',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'service_type__name': 'Photobooth'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_photobooth_options', to='contracts.additionaleventstaffoption'),
        ),
    ]
