# Generated by Django 4.2.3 on 2024-03-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0034_paymentpurpose_paymentschedule_schedulepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_type',
            new_name='payment_method',
        ),
    ]
