# Generated by Django 4.2.3 on 2024-03-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0035_rename_payment_type_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
