# Generated by Django 4.2.3 on 2024-03-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0036_payment_memo_payment_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='note',
            new_name='payment_reference',
        ),
    ]
