# Generated by Django 4.2.3 on 2024-03-13 16:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0037_rename_note_payment_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='other_discounts',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='package_discounts',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='sunday_discounts',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_type',
        ),
        migrations.AddField(
            model_name='contract',
            name='other_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_discounts', to='contracts.discount'),
        ),
        migrations.AddField(
            model_name='contract',
            name='package_discount_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contract',
            name='sunday_discount_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='discount',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.servicetype'),
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('Package', 'Package Discounts'), ('Sunday', 'Sunday Discounts')], max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('discount_type', 'version')},
            },
        ),
    ]
