# Generated by Django 4.2.3 on 2024-03-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0038_remove_contract_other_discounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='name',
        ),
        migrations.AddField(
            model_name='discount',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
