# Generated by Django 4.2.3 on 2024-03-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0039_remove_discount_is_active_remove_discount_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='other_discount',
        ),
        migrations.AddField(
            model_name='contract',
            name='other_discounts',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='contracts.discount'),
        ),
    ]
