# Generated by Django 4.2.3 on 2024-03-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0040_remove_contract_other_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
