# Generated by Django 4.2.3 on 2024-03-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0041_alter_contract_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='booked_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
