# Generated by Django 4.2.3 on 2024-04-06 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0042_contract_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='partner_phone1',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='partner_phone2',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_phone1',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_phone2',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ceremony_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='reception_phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format XXX-XXX-XXXX.', regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
    ]
