# Generated by Django 4.2.3 on 2024-06-10 14:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0043_alter_client_alt_phone_alter_client_partner_phone1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),

        migrations.AddField(
            model_name='additionaleventstaffoption',
            name='rider_text',
            field=models.TextField(blank=True, help_text='Rider for the package'),
        ),
        migrations.AddField(
            model_name='availability',
            name='always_off_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='contract',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_coordinated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='custom_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='old_contract_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='photobooth_op1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_op1_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='photobooth_op2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_op2_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='is_client_visible',
            field=models.BooleanField(default=True, help_text='Check if this document should be visible to clients.'),
        ),
        migrations.AddField(
            model_name='engagementsessionoption',
            name='rider_text',
            field=models.TextField(blank=True, help_text='Rider for the package'),
        ),
        migrations.AddField(
            model_name='engagementsessionoption',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_session_options', to='contracts.servicetype'),
        ),
        migrations.AddField(
            model_name='overtimeoption',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='rider_text',
            field=models.TextField(blank=True, help_text='Rider for the package'),
        ),
        migrations.AddField(
            model_name='payment',
            name='modified_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.paymentpurpose'),
        ),
        migrations.AddField(
            model_name='staffovertime',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'photographer1'), ('PHOTOGRAPHER2', 'photographer2'), ('VIDEOGRAPHER1', 'videographer1'), ('VIDEOGRAPHER2', 'videographer2'), ('DJ1', 'dj1'), ('DJ2', 'dj2'), ('PHOTOBOOTH_OP1', 'photobooth_op1'), ('PHOTOBOOTH_OP2', 'photobooth_op2'), ('PROSPECT1', 'prospect_photographer1'), ('PROSPECT2', 'prospect_photographer2'), ('PROSPECT3', 'prospect_photographer3'), ('ENGAGEMENT', 'engagement')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='booking_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='hours_booked',
            field=models.PositiveIntegerField(blank=True, choices=[(2, '2 Hours'), (4, '4 Hours'), (8, '8 Hours')], null=True),
        ),
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'Photographer 1'), ('PHOTOGRAPHER2', 'Photographer 2'), ('ENGAGEMENT', 'Engagement'), ('VIDEOGRAPHER1', 'Videographer 1'), ('VIDEOGRAPHER2', 'Videographer 2'), ('DJ1', 'DJ 1'), ('DJ2', 'DJ 2'), ('PHOTOBOOTH_OP1', 'Photobooth Operator 1'), ('PHOTOBOOTH_OP2', 'Photobooth Operator 2'), ('PROSPECT1', 'Prospect Photographer 1'), ('PROSPECT2', 'Prospect Photographer 2'), ('PROSPECT3', 'Prospect Photographer 3')], max_length=30),
        ),
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='status',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CLEARED', 'Cleared')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='overtimeoption',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'photographer1'), ('PHOTOGRAPHER2', 'photographer2'), ('VIDEOGRAPHER1', 'videographer1'), ('VIDEOGRAPHER2', 'videographer2'), ('DJ1', 'dj1'), ('DJ2', 'dj2'), ('PHOTOBOOTH_OP1', 'photobooth_op1'), ('PHOTOBOOTH_OP2', 'photobooth_op2'), ('PROSPECT1', 'prospect_photographer1'), ('PROSPECT2', 'prospect_photographer2'), ('PROSPECT3', 'prospect_photographer3'), ('ENGAGEMENT', 'engagement')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='eventstaffbooking',
            unique_together={('contract', 'role')},
        ),
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('applied_date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicefees', to='contracts.contract')),
                ('fee_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.servicefeetype')),
            ],
        ),
        migrations.CreateModel(
            name='RiderAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_type', models.CharField(max_length=50)),
                ('signature', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rider_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_agreements', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photography_service', models.CharField(blank=True, max_length=255, null=True)),
                ('videography_service', models.CharField(blank=True, max_length=255, null=True)),
                ('dj_service', models.CharField(blank=True, max_length=255, null=True)),
                ('photobooth_service', models.CharField(blank=True, max_length=255, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_agreements', to='contracts.contract')),
                ('photographer_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', to='contracts.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
