# Generated by Django 4.2.3 on 2024-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0044_contract_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'Photographer 1'), ('PHOTOGRAPHER2', 'Photographer 2'), ('ENGAGEMENT', 'Engagement'), ('VIDEOGRAPHER1', 'Videographer 1'), ('VIDEOGRAPHER2', 'Videographer 2'), ('DJ1', 'DJ 1'), ('DJ2', 'DJ 2'), ('PHOTOBOOTH_OP', 'Photobooth Operator'), ('PROSPECT1', 'Prospect Photographer 1'), ('PROSPECT2', 'Prospect Photographer 2'), ('PROSPECT3', 'Prospect Photographer 3')], max_length=30),
        ),
    ]
