# Generated by Django 4.2.3 on 2024-04-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0047_alter_eventstaffbooking_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='booking_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='hours_booked',
            field=models.PositiveIntegerField(blank=True, choices=[(2, '2 Hours'), (4, '4 Hours'), (8, '8 Hours')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventstaffbooking',
            unique_together={('contract', 'role')},
        ),
    ]
