# Generated by Django 4.2.3 on 2024-04-19 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0049_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='modified_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
    ]
