# Generated by Django 4.2.3 on 2024-04-20 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0050_payment_modified_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', to='contracts.contract'),
            preserve_default=False,
        ),
    ]
