# Generated by Django 4.2.3 on 2024-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0051_changelog_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='status',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
    ]
