# Generated by Django 4.2.3 on 2024-04-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0052_alter_eventstaffbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dj_custom_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='photobooth_custom_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='photography_custom_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='videography_custom_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
