# Generated by Django 4.2.3 on 2024-04-26 16:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0054_servicefee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefee',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicefee',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicefees', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='servicefee',
            name='description',
            field=models.TextField(),
        ),
    ]
