# Generated by Django 4.2.3 on 2024-04-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0055_alter_servicefee_amount_alter_servicefee_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefee',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
