# Generated by Django 4.2.3 on 2024-04-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0056_alter_servicefee_description'),
    ]

    operations = [
        # migrations.RemoveField(
          #  model_name='contractdocument',
           # name='is_visible',
#        ),
        migrations.AddField(
            model_name='contractdocument',
            name='is_client_visible',
            field=models.BooleanField(default=True, help_text='Check if this document should be visible to clients.'),
        ),
    ]
