# Generated by Django 4.2.3 on 2024-05-04 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0057_remove_contractdocument_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementsessionoption',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_session_options', to='contracts.servicetype'),
        ),
    ]
