# Generated by Django 4.2.3 on 2024-05-09 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0059_availability_always_off_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('staff', 'date')},
        ),
    ]
