# Generated by Django 4.2.3 on 2024-05-09 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_user_type'),
        ('contracts', '0060_alter_availability_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAlwaysOffDays',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('always_off_days', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='availability',
            name='always_off_days',
        ),
    ]
