# Generated by Django 4.2.3 on 2024-05-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0061_staffalwaysoffdays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='always_off_days',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StaffAlwaysOffDays',
        ),
    ]
