# Generated by Django 4.2.3 on 2024-05-14 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0062_availability_always_off_days_alter_availability_date_and_more'),
    ]

    operations = [


        migrations.AddField(
            model_name='contract',
            name='photobooth_op1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth1_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='photobooth_op2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth2_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
