# Generated by Django 4.2.3 on 2024-05-14 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0063_remove_contract_photobooth_op_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='contract',
            name='photobooth_op',
        ),
        migrations.RemoveField(
            model_name='contractdocument',
            name='is_visible',
        ),

        migrations.AlterField(
            model_name='contract',
            name='photobooth_op1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_op1_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='photobooth_op2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photobooth_op2_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
