# Generated by Django 4.2.3 on 2024-05-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0064_alter_contract_photobooth_op1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'Photographer 1'), ('PHOTOGRAPHER2', 'Photographer 2'), ('ENGAGEMENT', 'Engagement'), ('VIDEOGRAPHER1', 'Videographer 1'), ('VIDEOGRAPHER2', 'Videographer 2'), ('DJ1', 'DJ 1'), ('DJ2', 'DJ 2'), ('PHOTOBOOTH_OP1', 'Photobooth Operator 1'), ('PHOTOBOOTH_OP2', 'Photobooth Operator 2'), ('PROSPECT1', 'Prospect Photographer 1'), ('PROSPECT2', 'Prospect Photographer 2'), ('PROSPECT3', 'Prospect Photographer 3')], max_length=30),
        ),
    ]
