# Generated by Django 4.2.3 on 2024-05-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0065_alter_eventstaffbooking_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.paymentpurpose'),
        ),
    ]
