# Generated by Django 4.2.3 on 2024-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0066_payment_payment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefee',
            name='fee_type',
            field=models.CharField(default='CC Processing Fee', max_length=50),
        ),
    ]
