# Generated by Django 4.2.3 on 2024-05-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0067_servicefee_fee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='servicefee',
            name='fee_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.servicefeetype'),
        ),
    ]
