# Generated by Django 4.2.3 on 2024-05-17 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0068_servicefeetype_alter_servicefee_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeoption',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='overtimeoption',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
