# Generated by Django 4.2.3 on 2024-05-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0069_overtimeoption_name_alter_overtimeoption_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffovertime',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'photographer1'), ('PHOTOGRAPHER2', 'photographer2'), ('VIDEOGRAPHER1', 'videographer1'), ('VIDEOGRAPHER2', 'videographer2'), ('DJ1', 'dj1'), ('DJ2', 'dj2'), ('PHOTOBOOTH_OP1', 'photobooth_op1'), ('PHOTOBOOTH_OP2', 'photobooth_op2')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='overtimeoption',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'photographer1'), ('PHOTOGRAPHER2', 'photographer2'), ('VIDEOGRAPHER1', 'videographer1'), ('VIDEOGRAPHER2', 'videographer2'), ('DJ1', 'dj1'), ('DJ2', 'dj2'), ('PHOTOBOOTH_OP1', 'photobooth_op1'), ('PHOTOBOOTH_OP2', 'photobooth_op2')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
