# Generated by Django 4.2.3 on 2024-05-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0070_staffovertime_role_alter_overtimeoption_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='dj_custom_text',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='photobooth_custom_text',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='photography_custom_text',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='videography_custom_text',
        ),
        migrations.AddField(
            model_name='contract',
            name='custom_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
