# Generated by Django 4.2.3 on 2024-05-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0071_remove_contract_dj_custom_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='old_contract_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
