# Generated by Django 4.2.3 on 2024-05-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0072_contract_old_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaleventstaffoption',
            name='rider_text',
            field=models.TextField(blank=True, help_text='Rider for the package'),
        ),
        migrations.AddField(
            model_name='engagementsessionoption',
            name='rider_text',
            field=models.TextField(blank=True, help_text='Rider for the package'),
        ),
        migrations.AddField(
            model_name='package',
            name='rider_text',
            field=models.TextField(blank=True, help_text='Rider for the package'),
        ),
    ]
