# Generated by Django 4.2.3 on 2024-05-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0074_rideragreement_contractagreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractagreement',
            name='initials',
        ),
    ]
