# Generated by Django 4.2.3 on 2024-05-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0075_remove_contractagreement_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideragreement',
            name='rider_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
