# Generated by Django 4.2.3 on 2024-05-27 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0076_rideragreement_rider_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractagreement',
            name='photographer_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
