# Generated by Django 4.2.3 on 2024-05-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0077_contractagreement_photographer_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='old_contract_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
