# Generated by Django 4.2.3 on 2024-05-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0078_alter_contract_old_contract_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicefee',
            name='name',
        ),
        migrations.AddField(
            model_name='servicefee',
            name='applied_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
