# Generated by Django 4.2.3 on 2024-05-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0079_remove_servicefee_name_servicefee_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='status',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CLEARED', 'Cleared')], default='PENDING', max_length=20),
        ),
    ]
