# Generated by Django 4.2.3 on 2024-05-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0080_alter_eventstaffbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimeoption',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'photographer1'), ('PHOTOGRAPHER2', 'photographer2'), ('VIDEOGRAPHER1', 'videographer1'), ('VIDEOGRAPHER2', 'videographer2'), ('DJ1', 'dj1'), ('DJ2', 'dj2'), ('PHOTOBOOTH_OP1', 'photobooth_op1'), ('PHOTOBOOTH_OP2', 'photobooth_op2'), ('PROSPECT1', 'prospect_photographer1'), ('PROSPECT2', 'prospect_photographer2'), ('PROSPECT3', 'prospect_photographer3'), ('ENGAGEMENT', 'engagement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffovertime',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER1', 'photographer1'), ('PHOTOGRAPHER2', 'photographer2'), ('VIDEOGRAPHER1', 'videographer1'), ('VIDEOGRAPHER2', 'videographer2'), ('DJ1', 'dj1'), ('DJ2', 'dj2'), ('PHOTOBOOTH_OP1', 'photobooth_op1'), ('PHOTOBOOTH_OP2', 'photobooth_op2'), ('PROSPECT1', 'prospect_photographer1'), ('PROSPECT2', 'prospect_photographer2'), ('PROSPECT3', 'prospect_photographer3'), ('ENGAGEMENT', 'engagement')], max_length=50),
        ),
    ]
