# Generated by Django 4.2.3 on 2024-06-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0081_alter_overtimeoption_role_alter_staffovertime_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractagreement',
            name='version_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractagreement',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_agreements', to='contracts.contract'),
        ),
    ]
