# Generated by Django 4.2.3 on 2024-06-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0082_contractagreement_version_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractagreement',
            name='dj_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractagreement',
            name='photobooth_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractagreement',
            name='photography_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractagreement',
            name='videography_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
