# Generated by Django 4.2.3 on 2024-06-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0083_contractagreement_dj_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pipeline', 'Pipeline'), ('forecast', 'Forecast'), ('booked', 'Booked'), ('completed', 'Completed'), ('dead', 'Dead')], default='pipeline', max_length=10),
        ),
    ]
