# Generated by Django 4.2.3 on 2024-06-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0044_servicefeetype_remove_contract_photobooth_op_and_more'),
        ('contracts', '0083_contractagreement_dj_service_and_more'),
    ]

    operations = [
    ]
