# Generated by Django 4.2.3 on 2024-06-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0084_alter_contract_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='lead_source',
            new_name='lead_source_category',
        ),
        migrations.AddField(
            model_name='contract',
            name='lead_source_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
