# Generated by Django 4.2.3 on 2024-06-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0085_rename_lead_source_contract_lead_source_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ONLINE', 'Online'), ('REFERRAL', 'Referral')], max_length=20)),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='lead_source_category',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='lead_source_details',
        ),
        migrations.AddField(
            model_name='contract',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.leadsource'),
        ),
    ]
