# Generated by Django 4.2.3 on 2024-06-13 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0086_leadsource_remove_contract_lead_source_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='lead_source',
        ),
        migrations.AddField(
            model_name='contract',
            name='lead_source_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='LeadSource',
        ),
        migrations.AddField(
            model_name='contract',
            name='lead_source_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.leadsourcecategory'),
        ),
    ]
