# Generated by Django 4.2.3 on 2024-06-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0084_merge_20240610_0937'),
        ('contracts', '0087_leadsourcecategory_remove_contract_lead_source_and_more'),
    ]

    operations = [
    ]
