# Generated by Django 4.2.3 on 2024-06-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0087_leadsourcecategory_remove_contract_lead_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingDayGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('primary_contact', models.CharField(max_length=255)),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(max_length=15)),
                ('partner_contact', models.CharField(max_length=255)),
                ('partner_email', models.EmailField(max_length=254)),
                ('partner_phone', models.CharField(max_length=15)),
                ('dressing_location', models.CharField(max_length=255)),
                ('dressing_address', models.CharField(max_length=255)),
                ('dressing_start_time', models.TimeField()),
                ('ceremony_location', models.CharField(max_length=255)),
                ('ceremony_address', models.CharField(max_length=255)),
                ('ceremony_phone', models.CharField(max_length=15)),
                ('ceremony_start', models.TimeField()),
                ('ceremony_end', models.TimeField()),
                ('reception_location', models.CharField(max_length=255)),
                ('reception_address', models.CharField(max_length=255)),
                ('reception_phone', models.CharField(max_length=15)),
                ('reception_start', models.TimeField()),
                ('reception_end', models.TimeField()),
                ('staff_table', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop1', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop2', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop3', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop4', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer2_start_location', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer2_start_location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer2_start', models.TimeField(blank=True, null=True)),
                ('maid_of_honor', models.CharField(max_length=255)),
                ('bridesmaids_qty', models.IntegerField()),
                ('flower_girl_qty', models.IntegerField()),
                ('usher_qty', models.IntegerField()),
                ('best_man', models.CharField(max_length=255)),
                ('groomsmen_qty', models.IntegerField()),
                ('ring_bearer_qty', models.IntegerField()),
                ('bride_parents_names', models.TextField()),
                ('bride_sibling_names', models.TextField()),
                ('bride_grandparents_names', models.TextField()),
                ('groom_parents_names', models.TextField()),
                ('groom_siblings_names', models.TextField()),
                ('groom_grandparents_names', models.TextField()),
                ('additional_photo_request1', models.TextField(blank=True, null=True)),
                ('additional_photo_request2', models.TextField(blank=True, null=True)),
                ('additional_photo_request3', models.TextField(blank=True, null=True)),
                ('additional_photo_request4', models.TextField(blank=True, null=True)),
                ('additional_photo_request5', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.client')),
            ],
        ),
    ]
