# Generated by Django 4.2.3 on 2024-06-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0088_merge_20240626_1336'),
        ('contracts', '0088_weddingdayguide'),
    ]

    operations = [
    ]
