# Generated by Django 4.2.3 on 2024-08-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0088_weddingdayguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingdayguide',
            name='ceremony_location',
        ),
        migrations.RemoveField(
            model_name='weddingdayguide',
            name='client',
        ),
        migrations.RemoveField(
            model_name='weddingdayguide',
            name='reception_location',
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='ceremony_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='contract',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='wedding_day_guide', to='contracts.contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='dance_montage_song_artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='dance_montage_song_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='dinner_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='photo_booth_placement',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='photo_booth_text_line1',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='photo_booth_text_line2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='reception_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='video_client_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='video_special_dances',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='wedding_story_song_artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='wedding_story_song_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='additional_photo_request1',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='additional_photo_request2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='additional_photo_request3',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='additional_photo_request4',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='additional_photo_request5',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='best_man',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='bride_grandparents_names',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='bride_parents_names',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='bride_sibling_names',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='bridesmaids_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='ceremony_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='ceremony_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='ceremony_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='ceremony_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='dressing_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='dressing_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='flower_girl_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='groom_grandparents_names',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='groom_parents_names',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='groom_siblings_names',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='groomsmen_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='maid_of_honor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='partner_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='partner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='partner_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='reception_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='reception_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='reception_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='reception_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='ring_bearer_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='usher_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
