# Generated by Django 4.2.3 on 2024-06-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0089_merge_0088_merge_20240626_1336_0088_weddingdayguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingdayguide',
            name='client',
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='contract',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wedding_day_guide', to='contracts.contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
