# Generated by Django 4.2.3 on 2024-08-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
      #  ('contracts', '0089_remove_weddingdayguide_ceremony_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeddingDayGuide',
        ),
    ]
