# Generated by Django 4.2.3 on 2024-08-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('contracts', '0090_delete_weddingdayguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingDayGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('primary_contact', models.CharField(max_length=255)),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(max_length=15)),
                ('partner_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('partner_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dressing_location', models.CharField(max_length=255)),
                ('dressing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('dressing_start_time', models.TimeField(blank=True, null=True)),
                ('ceremony_site', models.CharField(blank=True, max_length=255, null=True)),
                ('ceremony_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ceremony_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('ceremony_start', models.TimeField(blank=True, null=True)),
                ('ceremony_end', models.TimeField(blank=True, null=True)),
                ('reception_site', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_address', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('reception_start', models.TimeField(blank=True, null=True)),
                ('dinner_start', models.TimeField(blank=True, null=True)),
                ('reception_end', models.TimeField(blank=True, null=True)),
                ('staff_table', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop1', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop2', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop3', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_stop4', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer2_start_location', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer2_start_location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer2_start', models.TimeField(blank=True, null=True)),
                ('maid_of_honor', models.CharField(blank=True, max_length=255, null=True)),
                ('bridesmaids_qty', models.IntegerField(blank=True, null=True)),
                ('flower_girl_qty', models.IntegerField(blank=True, null=True)),
                ('usher_qty', models.IntegerField(blank=True, null=True)),
                ('best_man', models.CharField(blank=True, max_length=255, null=True)),
                ('groomsmen_qty', models.IntegerField(blank=True, null=True)),
                ('ring_bearer_qty', models.IntegerField(blank=True, null=True)),
                ('bride_parents_names', models.TextField(blank=True, max_length=255, null=True)),
                ('bride_sibling_names', models.TextField(blank=True, max_length=255, null=True)),
                ('bride_grandparents_names', models.TextField(blank=True, max_length=255, null=True)),
                ('groom_parents_names', models.TextField(blank=True, max_length=255, null=True)),
                ('groom_siblings_names', models.TextField(blank=True, max_length=255, null=True)),
                ('groom_grandparents_names', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request1', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request2', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request3', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request4', models.TextField(blank=True, max_length=255, null=True)),
                ('additional_photo_request5', models.TextField(blank=True, max_length=255, null=True)),
                ('video_client_names', models.CharField(blank=True, max_length=255, null=True)),
                ('wedding_story_song_title', models.CharField(blank=True, max_length=255, null=True)),
                ('wedding_story_song_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('dance_montage_song_title', models.CharField(blank=True, max_length=255, null=True)),
                ('dance_montage_song_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('video_special_dances', models.TextField(blank=True, max_length=255, null=True)),
                ('photo_booth_text_line1', models.TextField(blank=True, max_length=255, null=True)),
                ('photo_booth_text_line2', models.TextField(blank=True, max_length=255, null=True)),
                ('photo_booth_placement', models.TextField(blank=True, max_length=255, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_day_guide', to='contracts.contract')),
            ],
        ),
    ]
