# Generated by Django 4.2.3 on 2024-08-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0091_weddingdayguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingdayguide',
            name='dressing_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='primary_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='weddingdayguide',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
