# Generated by Django 4.2.3 on 2024-08-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0092_alter_weddingdayguide_dressing_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='flower_girl_qty',
            new_name='flower_attendant_qty',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='best_man',
            new_name='p1_attendant_of_honor',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='bridesmaids_qty',
            new_name='p1_attendant_qty',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='bride_grandparents_names',
            new_name='p1_grandparents_names',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='bride_parents_names',
            new_name='p1_parents_names',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='bride_sibling_names',
            new_name='p1_sibling_names',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='groom_grandparents_names',
            new_name='p2_grandparents_names',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='groom_parents_names',
            new_name='p2_parents_names',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='groom_siblings_names',
            new_name='p2_siblings_names',
        ),
        migrations.RemoveField(
            model_name='weddingdayguide',
            name='maid_of_honor',
        ),
        migrations.AddField(
            model_name='weddingdayguide',
            name='p2_attendant_of_honor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
