# Generated by Django 4.2.3 on 2024-08-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0093_rename_flower_girl_qty_weddingdayguide_flower_attendant_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='p1_grandparents_names',
            new_name='p1_grandparent_names',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='p1_parents_names',
            new_name='p1_parent_names',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='groomsmen_qty',
            new_name='p2_attendant_qty',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='p2_grandparents_names',
            new_name='p2_grandparent_names',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='p2_parents_names',
            new_name='p2_parent_names',
        ),
        migrations.RenameField(
            model_name='weddingdayguide',
            old_name='p2_siblings_names',
            new_name='p2_sibling_names',
        ),
    ]
