# Generated by Django 4.2.3 on 2024-08-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0094_rename_p1_grandparents_names_weddingdayguide_p1_grandparent_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingdayguide',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
    ]
