# Generated by Django 4.2.3 on 2024-11-28 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0013_remove_additionaleventstaffoption_service_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PHOTOGRAPHER1', 'photographer1'), ('PHOTOGRAPHER2', 'photographer2'), ('VIDEOGRAPHER1', 'videographer1'), ('VIDEOGRAPHER2', 'videographer2'), ('DJ1', 'dj1'), ('DJ2', 'dj2'), ('PHOTOBOOTH_OP1', 'photobooth_op1'), ('PHOTOBOOTH_OP2', 'photobooth_op2'), ('PROSPECT1', 'prospect_photographer1'), ('PROSPECT2', 'prospect_photographer2'), ('PROSPECT3', 'prospect_photographer3'), ('ENGAGEMENT', 'engagement')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffOvertime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PHOTOGRAPHER1', 'photographer1'), ('PHOTOGRAPHER2', 'photographer2'), ('VIDEOGRAPHER1', 'videographer1'), ('VIDEOGRAPHER2', 'videographer2'), ('DJ1', 'dj1'), ('DJ2', 'dj2'), ('PHOTOBOOTH_OP1', 'photobooth_op1'), ('PHOTOBOOTH_OP2', 'photobooth_op2'), ('PROSPECT1', 'prospect_photographer1'), ('PROSPECT2', 'prospect_photographer2'), ('PROSPECT3', 'prospect_photographer3'), ('ENGAGEMENT', 'engagement')], max_length=50)),
                ('overtime_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('overtime_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.overtimeoption')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Deposit Amount')),
                ('hours', models.IntegerField(default=0, verbose_name='Hours')),
                ('default_text', models.TextField(blank=True, help_text='Default text for the package')),
                ('rider_text', models.TextField(blank=True, help_text='Rider for the package')),
                ('package_notes', models.TextField(blank=True, help_text='Additional notes for the package')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.servicetype')),
            ],
        ),
        migrations.AddField(
            model_name='overtimeoption',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_options', to='services.servicetype'),
        ),
        migrations.CreateModel(
            name='EngagementSessionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Deposit Amount')),
                ('default_text', models.TextField(blank=True, help_text='Default text for the package')),
                ('rider_text', models.TextField(blank=True, help_text='Rider for the package')),
                ('package_notes', models.TextField(blank=True, help_text='Additional notes for the package')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_session_options', to='services.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='ContractOvertime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='contracts.contract')),
                ('overtime_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.overtimeoption')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalEventStaffOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Deposit Amount')),
                ('hours', models.IntegerField(default=0, verbose_name='Hours')),
                ('default_text', models.TextField(blank=True, help_text='Default text for the staff option')),
                ('rider_text', models.TextField(blank=True, help_text='Rider for the package')),
                ('package_notes', models.TextField(blank=True, help_text='Additional notes for the staff option')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_staff_options', to='services.servicetype')),
            ],
        ),
    ]
