# Generated by Django 4.2.3 on 2025-02-14 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaleventstaffoption',
            name='default_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Default text for the additional option'),
        ),
        migrations.AlterField(
            model_name='additionaleventstaffoption',
            name='rider_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rider text for the additional option'),
        ),
        migrations.AlterField(
            model_name='engagementsessionoption',
            name='default_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Default text for the engagement session'),
        ),
        migrations.AlterField(
            model_name='engagementsessionoption',
            name='rider_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rider text for engagement session'),
        ),
        migrations.AlterField(
            model_name='package',
            name='default_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Default text for the package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='rider_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rider text for the package'),
        ),
    ]
