# Generated by Django 4.2.3 on 2024-11-13 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0007_remove_contractdocument_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_type', models.CharField(max_length=50)),
                ('signature', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rider_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_agreements', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='contract_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_client_visible', models.BooleanField(default=True, help_text='Check if this document should be visible to clients.')),
                ('is_event_staff_visible', models.BooleanField(default=False, help_text='Check if this document should be visible to event staff.')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photography_service', models.CharField(blank=True, max_length=255, null=True)),
                ('videography_service', models.CharField(blank=True, max_length=255, null=True)),
                ('dj_service', models.CharField(blank=True, max_length=255, null=True)),
                ('photobooth_service', models.CharField(blank=True, max_length=255, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_agreements', to='contracts.contract')),
                ('photographer_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
