# Generated by Django 4.2.3 on 2025-02-08 14:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0014_alter_contract_dj_additional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalwearProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rental_type', models.CharField(choices=[('TUXEDO', 'Tuxedo'), ('DRESS', 'Dress'), ('SHOES', 'Shoes'), ('ACCESSORIES', 'Accessories')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('rental_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Version of the product.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractFormalwearProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('rental_start_date', models.DateField()),
                ('rental_return_date', models.DateField()),
                ('returned', models.BooleanField(default=False)),
                ('product_version', models.PositiveIntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formalwear_contracts', to='contracts.contract')),
                ('formalwear_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formalwear.formalwearproduct')),
            ],
        ),
    ]
