# Generated by Django 4.2.3 on 2025-02-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formalwear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalwearproduct',
            name='default_text',
            field=models.TextField(blank=True, help_text='Default instructions for rental.', null=True),
        ),
        migrations.AddField(
            model_name='formalwearproduct',
            name='rider',
            field=models.TextField(blank=True, help_text='Contract-specific rider terms.', null=True),
        ),

    ]
