# Generated by Django 4.2.3 on 2025-02-09 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formalwear', '0002_formalwearproduct_default_text_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='contractformalwearproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contractformalwearproduct',
            name='rental_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractformalwearproduct',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
