# Generated by Django 4.2.3 on 2025-02-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formalwear', '0004_remove_contractformalwearproduct_product_version_and_more'),
    ]

    migrations.RemoveField(
        model_name='contractformalwearproduct',
        name='product_version',
    )

