# Generated by Django 4.2.3 on 2025-02-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formalwear', '0005_remove_contractformalwearproduct_product_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractformalwearproduct',
            name='product_version',
        ),
    ]
