# Generated by Django 4.2.3 on 2025-02-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formalwear', '0006_remove_contractformalwearproduct_product_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formalwearproduct',
            old_name='is_available',
            new_name='is_active',
        ),
    ]
