# Generated by Django 4.2.3 on 2025-02-11 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_contract_formalwear_products'),
        ('formalwear', '0007_rename_is_available_formalwearproduct_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formalwearproduct',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contractformalwearproduct',
            name='contract',
            field=models.ForeignKey(help_text='The contract associated with this formalwear product rental.', on_delete=django.db.models.deletion.CASCADE, related_name='formalwear_contracts', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='contractformalwearproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this formalwear product rental was created.'),
        ),
        migrations.AlterField(
            model_name='contractformalwearproduct',
            name='formalwear_product',
            field=models.ForeignKey(help_text='The formalwear product being rented within the contract.', on_delete=django.db.models.deletion.CASCADE, related_name='formalwear_product', to='formalwear.formalwearproduct'),
        ),
        migrations.AlterField(
            model_name='contractformalwearproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='The number of units of the formalwear product being rented.'),
        ),
        migrations.AlterField(
            model_name='contractformalwearproduct',
            name='rental_return_date',
            field=models.DateField(blank=True, help_text='The date by which the formalwear product is expected to be returned.', null=True),
        ),
        migrations.AlterField(
            model_name='contractformalwearproduct',
            name='rental_start_date',
            field=models.DateField(blank=True, help_text='The date when the rental period starts for this formalwear product.', null=True),
        ),
        migrations.AlterField(
            model_name='contractformalwearproduct',
            name='returned',
            field=models.BooleanField(default=False, help_text='Indicates whether the formalwear product has been returned.'),
        ),
    ]
