# Generated by Django 4.2.3 on 2025-02-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formalwear', '0008_remove_formalwearproduct_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formalwearproduct',
            name='created_at',
        ),
    ]
