# Generated by Django 4.2.3 on 2025-02-14 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formalwear', '0009_remove_formalwearproduct_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalwearproduct',
            name='default_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Default text for the formalwear product', null=True),
        ),
        migrations.AlterField(
            model_name='formalwearproduct',
            name='rider',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rider text for the formalwear product', null=True),
        ),
    ]
