# Generated by Django 4.2.3 on 2024-01-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedcommunication',
            name='note_type',
            field=models.CharField(choices=[('office', 'Office Note'), ('contract', 'Contract Note')], max_length=10, verbose_name='Note Type'),
        ),
    ]
