# Generated by Django 4.2.3 on 2024-08-17 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_changelog_contractagreement_contractdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiedcommunication',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='unifiedcommunication',
            name='object_id',
        ),
        migrations.AddField(
            model_name='unifiedcommunication',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='contracts.contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='unifiedcommunication',
            name='note_type',
            field=models.CharField(choices=[('internal', 'Internal Note'), ('portal', 'Portal Note'), ('booking', 'Booking Note')], max_length=10, verbose_name='Note Type'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('type', models.CharField(choices=[('contract', 'Contract'), ('internal', 'Internal')], default='internal', max_length=10)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.unifiedcommunication', verbose_name='Note')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
