# Generated by Django 4.2.3 on 2024-10-30 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contractdocument_is_event_staff_visible'),
        ('communication', '0002_remove_unifiedcommunication_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('contract', 'Contract'), ('internal', 'Internal')], default='internal', max_length=10, verbose_name='Task Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(db_index=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='unifiedcommunication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='unifiedcommunication',
            name='note_type',
            field=models.CharField(choices=[('internal', 'Internal Note'), ('portal', 'Portal Note'), ('booking', 'Booking Note')], db_index=True, max_length=10, verbose_name='Note Type'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'created_at'], name='communicati_due_dat_5117b4_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedcommunication',
            index=models.Index(fields=['created_at', 'note_type'], name='communicati_created_3e9613_idx'),
        ),
    ]
