# Generated by Django 4.2.3 on 2024-11-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_remove_task_type_task_task_type_alter_task_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedcommunication',
            name='note_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal Note'), ('PORTAL', 'Portal Note'), ('BOOKING', 'Booking Note')], db_index=True, max_length=10, verbose_name='Note Type'),
        ),
    ]
