# Generated by Django 4.2.3 on 2024-03-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.unifiedcommunication', verbose_name='Note'),
        ),
    ]
