# Generated by Django 4.2.3 on 2024-03-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0040_remove_contract_other_discount_and_more'),
        ('communication', '0004_alter_task_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
    ]
