# Generated by Django 4.2.3 on 2024-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_alter_task_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedcommunication',
            name='note_type',
            field=models.CharField(choices=[('office', 'Office Note'), ('contract', 'Contract Note'), ('booking_note', 'Booking Note')], max_length=15, verbose_name='Note Type'),
        ),
    ]
