# Generated by Django 4.2.3 on 2024-06-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_alter_unifiedcommunication_note_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('contract', 'Contract'), ('internal', 'Internal')], default='internal', max_length=10),
        ),
    ]
