# Generated by Django 4.2.3 on 2024-06-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0084_alter_contract_status'),
        ('communication', '0010_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiedcommunication',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='unifiedcommunication',
            name='object_id',
        ),
        migrations.AddField(
            model_name='unifiedcommunication',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='contracts.contract', verbose_name='Contract'),
        ),
    ]
