# Generated by Django 4.2.3 on 2024-11-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstaffbooking',
            name='hours_booked',
            field=models.PositiveIntegerField(blank=True, choices=[(2, '2 Hours'), (4, '4 Hours'), (6, '6 Hours'), (8, '8 Hours')], null=True),
        ),
    ]
