# Generated by Django 4.2.3 on 2025-02-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_eventstaffbooking_hours_booked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstaffbooking',
            options={'ordering': ['contract__event_date', 'role']},
        ),
        migrations.AlterUniqueTogether(
            name='eventstaffbooking',
            unique_together=set(),
        ),
    ]
