# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AdditionalProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(max_digits=5, decimal_places=2)),
                ('cost', models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)),
                ('is_taxable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('default_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('special_notes', models.TextField(blank=True, null=True)),
                # Temporarily omit the foreign keys
            ],
        ),
    ]
