# Generated by Django 4.2.3 on 2024-11-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_contractproduct_contract_contractproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalproduct',
            name='default_text',
            field=models.TextField(blank=True, help_text='Default text for products'),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
