# Generated by Django 4.2.3 on 2024-11-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_alter_contract_dj_additional_and_more'),
        ('products', '0003_alter_additionalproduct_default_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalproduct',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal cost of the product.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='default_text',
            field=models.TextField(blank=True, help_text='Default text or instructions associated with this product. This can be used for contracts.'),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the product.', null=True),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='is_taxable',
            field=models.BooleanField(default=False, help_text='Indicates whether this product is taxable.'),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='name',
            field=models.CharField(help_text='Name of the product or service.', max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional internal notes about the product.', null=True),
        ),
        migrations.AlterField(
            model_name='additionalproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price charged to the customer for this product.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='contractproduct',
            name='contract',
            field=models.ForeignKey(help_text='The contract to which this product is associated.', on_delete=django.db.models.deletion.CASCADE, related_name='contract_products', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='contractproduct',
            name='product',
            field=models.ForeignKey(help_text='The product being added to the contract.', on_delete=django.db.models.deletion.CASCADE, related_name='product_contracts', to='products.additionalproduct'),
        ),
        migrations.AlterField(
            model_name='contractproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='The quantity of the product being added to the contract.'),
        ),
        migrations.AlterField(
            model_name='contractproduct',
            name='special_notes',
            field=models.TextField(blank=True, help_text='Optional notes or instructions specific to this product within this contract.', null=True),
        ),
    ]
