# Generated by Django 4.2.3 on 2024-11-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_additionalproduct_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproduct',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if this product is active.', verbose_name='Active'),
        ),
    ]
