# Generated by Django 4.2.3 on 2024-11-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_additionalproduct_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractproduct',
            name='post_event',
            field=models.BooleanField(default=False, help_text='Indicates if this product was added after the event date.'),
        ),
    ]
