# Generated by Django 4.2.3 on 2024-12-17 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_contractproduct_post_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractproduct',
            name='post_event',
        ),
        migrations.AddField(
            model_name='contractproduct',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time when this product was added to the contract.'),
            preserve_default=False,
        ),
    ]
