# Generated by Django 4.2.3 on 2025-02-14 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_contractproduct_post_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalproduct',
            name='default_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Default text for the product'),
        ),
    ]
